### ISSUE TITLE
Cover undefined gelmis.

### ISSUE THREAD

**Issue by yasintz** [ademilter/homepage#15]
https://github.com/ademilter/homepage/blob/9db97a0a9fe57c77610106642539d93b3020cedb/lib/raindrop.js#L25-L35
30. satirda cover yoksa default bir resim gonderebilir. `o.cover || 'url...'`
![Screenshot_17](https://user-images.githubusercontent.com/36041339/104109905-82c5ff80-52e3-11eb-8fae-65b5d8652e1f.png)

**Comment by ademilter** [comment]
gereksiz data kullanımından dolayı görselleri kaldırdım ve özülmüş oldu
